language: ruby
rvm:
  - 1.9.3
  - 2.2.2
env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=4.2.0"
gemfile:
  - view_components.gemfile
before_script:
  - bundle install
script:
  - bundle exec rake test
